apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: nsg6q1aou-go 
  janus-idp.io/tekton: nsg6q1aou-go
  backstage.io/kubernetes-id: nsg6q1aou-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nsg6q1aou-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml