apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nsg6q1aou-go
  janus-idp.io/tekton: nsg6q1aou-go
  backstage.io/kubernetes-id: nsg6q1aou-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nsg6q1aou-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
