apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nsg6q1aou-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nsg6q1aou-go 
  name: nsg6q1aou-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nsg6q1aou-go 
